---

- include: ../../../centos-pkgs/pip/tasks/main.yml
  when: (ansible_os_family == "RedHat" or ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")

- include: ../../../ubuntu-pkgs/pip/tasks/main.yml
  when: (ansible_os_family == "Debian"  or ansible_distribution == 'Ubuntu')

- name: update pip using pip
  pip: name=ansible state=latest

