---

# Install DHCP server
- name: Install the required  packages in Redhat derivatives
  yum: name=dhcp state=installed
  when: ansible_os_family == 'RedHat'


# Generate configuration
- name: Generate dhcpd.conf
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=0644 validate='/usr/sbin/dhcpd -t -cf %s'
  notify:
    - restart dhcpd


# Generate service configuration
- name: Generate DHCP service conf
  template: src=service.conf.{{ ansible_os_family }}.j2 dest={{ dhcp_service_config }} owner=root group=root
  when: ansible_os_family == 'Debian' or (ansible_os_family == 'RedHat' and ansible_distribution_major_version < '7')
  notify:
    - restart dhcpd


# Enable DHCP server
- name: Start the dhcp services DHCP
  service: name=dhcpd state=started enabled=yes

