---

- name: upgrade/update all packages
  yum: name=* state=latest
  when: (ansible_os_family == "RedHat" or ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")
