---

- debug: msg="vagrant installation on CentOS machine"

- name: install vagrant
  yum: name=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.rpm state=present
  when: (ansible_os_family == "RedHat" or ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")
